name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.4' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Running tests
        run: pytest

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "e1900288-final-project" #Must be unique in Heroku
          heroku_email: "e1900288@edu.vamk.fi"
        env:
          HD_SECRET_KEY: ${{secrets.SECRET_KEY}}